# These are Global constants to use throughout the game
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

LASER_RADIUS = 30
LASER_SPEED = 10
LASER_LIFE = 60

SHIP_RADIUS = 30

INITIAL_ASTEROID_COUNT = 5

BIG_ASTEROID_SPIN = 1
BIG_ASTEROID_SPEED = 1.5
BIG_ASTEROID_RADIUS = 15

MEDIUM_ASTEROID_SPIN = -2
MEDIUM_ASTEROID_RADIUS = 5

SMALL_ASTEROID_SPIN = 5
SMALL_ASTEROID_RADIUS = 2